baseURL = "/"
enableInlineShortcodes = true
languageCode = "pt-br"
theme = "basedoff"
title = "Sobre desenho"
defaultcontentlanguage = "pt"
timeout = "600000"
[params]
customCss = ["lightbox2/css/lightbox.min.css", "css/custom.css"]
customJs = ["js/jquery.js", "lightbox2/js/lightbox.min.js", "js/main.js"]
defaultImageFit = "600x600"
defaultImageMaxFit = "1200x1200"
thumb-crop = "150x150 smart"
subtitle = "Marcia Cymbalista"
[markup.goldmark.renderer]
unsafe = true
[[menu.main]]
name = "Contato"
url = "/contato"
weight = 4
[[menu.main]]
name = "Currículo"
url = "/curriculo"
weight = 3
[[menu.main]]
name = "Educação"
url = "/educacao"
weight = 2
[[menu.main]]
name = "Trabalhos Artísticos"
url = "/trabalhos-artisticos"
weight = 1
