baseURL = "/"
enableInlineShortcodes = true
languageCode = "pt-br"
theme = "basedoff"
title = "Sobre desenho"
[markup.goldmark.renderer]
unsafe = true
[[menu.main]]
name = "Contato"
url = "/contato"
weight = 4
[[menu.main]]
name = "Currículo"
url = "/curriculo"
weight = 3
[[menu.main]]
name = "Educação"
url = "/educacao"
weight = 2
[[menu.main]]
name = "Trabalhos Artísticos"
url = "/trabalhos-artisticos"
weight = 1
[params]
customCss = []
customJs = []
defaultImageFit = "800x800"
defaultThumbCrop = "150x150 smart"
subtitle = "Marcia Cymbalista"
