---
label: default
hide_body: false
fields:
- name: title
  type: text
  config:
    required: false
  label: Título
- name: date
  type: datetime
  label: Data da publicação
  description: ''
  config:
    required: false
    date_format: 
    time_format: 
    display_utc: false
  default: now
- name: draft
  type: boolean
  label: Em manutenção
  default: true
pages:
- content/homepage.md
